# Generated by Django 3.0.9 on 2022-02-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moverspackers', '0002_auto_20220218_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='shiftingdate',
            field=models.DateField(max_length=200, null=True),
        ),
    ]
